### ISSUE TITLE
Linux only: PCLVisualizer.close() does not close the window

### ISSUE THREAD

**Issue by tcavallari** [PointCloudLibrary/pcl#172]
#85 fixed the bug for Windows and MacOS but apparently that is not enough on Linux with vtk 5.8.

A quote from that thread that might help:

> I've looked into the pcl code and into some vtk references and it seems to me that the odd Linux behavior depends on a potentially incomplete implementation of the vtkRendererWindowInteractor's specialization for the X environment (I'm not 100% sure about this though, I don't have enough knowledge of the vtk internals).
> 
> What makes me think so is the following:
> The vtkRendererWindowInteractor's [TerminateApp](http://www.vtk.org/doc/nightly/html/classvtkRenderWindowInteractor.html#a538b1adf29d41c990bd494005c962eb7) documentation states that the function "should be overridden by platform dependent subclasses to provide a termination procedure if one is required." The [Win32](http://www.vtk.org/doc/nightly/html/classvtkWin32RenderWindowInteractor.html#a0626afa6903372c98c94679b7f255cab) and [MacOS](http://www.vtk.org/doc/nightly/html/classvtkCocoaRenderWindowInteractor.html#a7816085c19a420672e37bc8372e888fb) versions apparently are doing so but the [X version](http://www.vtk.org/doc/nightly/html/classvtkXRenderWindowInteractor.html#a2cc229d0bcba69569b3783660f48c367) has those "question marks" in the docs. That leaves me thinking that the implementation might have some issues.. 
> 
> Still, I'm not a vtk nor an X programming expert, I honestly have no idea. If someone else wants to take a look at this it might be better...

**Comment by KermMartian** [comment]
This bug appears to still be extant. Thanks in advance for any help with it.

**Comment by VictorLamoine** [comment]
Please append a message to the VTK bug report so that it gains visibility!

http://www.vtk.org/Bug/view.php?id=14985

**Comment by giacomodabisias** [comment]
Hi,
still no solution to that?

**Comment by KermMartian** [comment]
Nope, still no solution that I'm aware of. I bumped the VTK thread, for what it's worth.

**Comment by VictorLamoine** [comment]
Issue has moved to: https://gitlab.kitware.com/vtk/vtk/issues/14985

**Comment by IgniparousTempest** [comment]
With 1.8.0 this is still an issue.

**Comment by IgniparousTempest** [comment]
This has been fixed in 1.8.0: [https://gitlab.kitware.com/vtk/vtk/issues/14985](https://gitlab.kitware.com/vtk/vtk/issues/14985)

**Comment by VictorLamoine** [comment]
- Works with VTK trunk
- I did not test with VTK 1.8.1 release
- Does not work with VTK 1.8.0 release

I have tested with the latest VTK and PCL trunk; it works.

```cpp
#include <pcl/io/pcd_io.h>
#include <pcl/visualization/pcl_visualizer.h>

int main(void)
{
  {
    pcl::visualization::PCLVisualizer viewer;
    viewer.spin();
    viewer.close();
  }
  {
    pcl::visualization::PCLVisualizer viewer;
    viewer.spin();
    viewer.close();
  }

  return 0;
}
```

**Comment by taketwo** [comment]
The [merge request](https://gitlab.kitware.com/vtk/vtk/merge_requests/3155) that fixed the problem in VTK is marked for the 8.0.1 milestone, so I suppose this is the first version that has the problem fixed.

**Comment by Kaju-Bubanja** [comment]
This bug still seems to exist in some form in 1.9.1. When I run the above test the window does not close. When I use spinOnce instead of spin it closes but only in the test case, and because the whole program closes. When the program doesn't close the window also does not close. I'm using following code:
```
#include <pcl/visualization/pcl_visualizer.h>

int main(void)
{
  pcl::visualization::PCLVisualizer viewer;
  viewer.spinOnce();
  viewer.close();
  while(true){}
}
```
I guess this is a bug? Is there a way to close the window with another method or a workaround?

**Comment by yifan-hou** [comment]
@Kaju-Bubanja In my case, the line `while(true){}` was the cause of problem. Immediate pausing after viewer.close() will cause the viewer window to freeze, I don't know why. The code snippet above works for me:
```c++
#include <pcl/io/pcd_io.h>
#include <pcl/visualization/pcl_visualizer.h>

int main(void)
{
  {
    pcl::visualization::PCLVisualizer viewer;
    viewer.spin();
    viewer.close();
  }
  {
    pcl::visualization::PCLVisualizer viewer;
    viewer.spin();
    viewer.close();
  }

  return 0;
}
```

**Comment by PerceptMD** [comment]
I need to ask for some user input after visualizing clouds but the viewer does not close when quitted.
Setup: PCL1.11 and VTK8.2 on Ubuntu 20.04.
My code looks about like this:
```
{
	// setup viewer obj
	pcl::visualization::PCLVisualizer viewer ("ICP demo");
            // insert some clouds and stuff [...]
	// TODO viewer window does not close here!
	viewer.close(); // https://github.com/PointCloudLibrary/pcl/issues/172 (fixed in VTK8)
}
char type;
do
{
    cout << "Input user choice" << endl;
    cin >> type;
}
while( !cin.fail() && type!='1' && type!='2' && type!='n');
```
The viewer window wont close until the application ends.
I cant really get around that do {} while () thing to get user input. Any ideas on how to get the viewer window closed before continuing?

**Comment by vebjornjr** [comment]
Any updates on this? I experience the same behavior as @PerceptMD with PCL 1.11 and VTK 6.3 on Ubuntu 18.04.

**Comment by fabrizioschiano** [comment]
@vebjornjr , did you figure out how to solve this issue. I have the same problem on Ubuntu 20.04 and vtk7-7.1.1

**Comment by fabrizioschiano** [comment]
I also tried what is mentioned in https://github.com/PointCloudLibrary/pcl/issues/3959#issuecomment-653350894 without success.

**Comment by jjxxz233** [comment]
i have the same problem in ubuntu 18.04 + PCL 1.8.1 + VTK 7.1.1
Windows10 + PCL 1.8.1 + VTK 8.0 works fine
