### ISSUE TITLE
[compile error] PCL compile error in real_sense_2_grabber.cpp(294) when OpenMP is enabled with realsense installed via vcpkg

### ISSUE THREAD

**Issue by mynickmynick** [PointCloudLibrary/pcl#5664]
**Describe the error**
pcl updated to master doesn't compile on my machine with openMP enabled, using Visual Studio 2019 on Windows 10

Main Compile error:
..................\pcl\fork\pcl\io\src\real_sense_2_grabber.cpp(294): error C3016: 'index': index variable in OpenMP 'for' statement must have signed integral type

Details:
 [72/486] Building CXX object io\CMakeFiles\pcl_io.dir\src\real_sense_2_grabber.cpp.obj
  FAILED: io/CMakeFiles/pcl_io.dir/src/real_sense_2_grabber.cpp.obj 
  C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DPCLAPI_EXPORTS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -Iinclude -I..\..\..\common\include -I..\..\..\octree\include -I..\..\..\openni\include -I..\..\..\openni2\include -I..\..\..\ensenso\include -I..\..\..\davidSDK\include -I..\..\..\dssdk\include -I..\..\..\rssdk\include -I..\..\..\rssdk2\include -I..\..\..\pcap\include -I..\..\..\png\include -I..\..\..\vtk\include -I..\..\..\io\include -IC:\Users\..........\vcpkg\vcpkg\installed\x64-windows\include\eigen3 -IC:\Users\.......\vcpkg\vcpkg\installed\x64-windows\include\openni2 -IC:\Users\.......\vcpkg\vcpkg\installed\x64-windows\include -I..\..\..\recognition\include\pcl\recognition\3rdparty /DWIN32 /D_WINDOWS /W3 /GR /EHsc /bigobj /FS -openmp /MD /O2 /Ob2 /DNDEBUG   -DBOOST_ALL_NO_LIB -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -DNOMINMAX -DPCL_ONLY_CORE_POINT_TYPES  -D__SSE4_2__ -D__SSE4_1__ -D__SSSE3__ -D__SSE3__ -D__SSE2__ -D__SSE__ -openmp -std:c++14 /showIncludes /Foio\CMakeFiles\pcl_io.dir\src\real_sense_2_grabber.cpp.obj /Fdio\CMakeFiles\pcl_io.dir\ /FS -c ..\..\..\io\src\real_sense_2_grabber.cpp
..................\pcl\fork\pcl\io\src\real_sense_2_grabber.cpp(294): error C3016: 'index': index variable in OpenMP 'for' statement must have signed integral type
  ..\..\..\io\src\real_sense_2_grabber.cpp(229): note: see reference to function template instantiation 'std::shared_ptr<pcl::PointCloud<pcl::PointXYZ>> pcl::RealSense2Grabber::convertRealsensePointsToPointCloud<pcl::PointXYZ,pcl::RealSense2Grabber::convertDepthToPointXYZ::<lambda_5504f3ee7daf55e4dbb7b522799496b7>>(const rs2::points &,Functor)' being compiled
          with
          [
              Functor=pcl::RealSense2Grabber::convertDepthToPointXYZ::<lambda_5504f3ee7daf55e4dbb7b522799496b7>
          ]

**To Reproduce**
I am compiling With OpenMP enabled (disabling it the compilation is fine)

the realsense is installed with vcpkg

realsense2_DIR=............/vcpkg/vcpkg/installed/x64-windows/share/realsense2

..............\vcpkg> .\vcpkg list realsense
realsense2:x64-windows                            2.51.1              Intel® RealSense™ SDK 2.0 is a cross-platform...
realsense2[openni2]:x64-windows                                       Build Intel® RealSense™ OpenNI2 driver
realsense2[tools]:x64-windows                                         Build Intel® RealSense™ tools

vcpkg repo commit tag: 2023.01.09 of 3 months ago

**Your Environment (please complete the following information):**

 - windows 10
 - Compiler: Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
 - PCL Version 6703b1795cf1fb73d77a4943dc5c088abf55e86c

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, CUDA enabled? No

**Possible Solution**

compile and install realsense from its repo instead of using vcpkg

part of the code:

`
  template <typename PointT, typename Functor>
  typename pcl::PointCloud<PointT>::Ptr
  RealSense2Grabber::convertRealsensePointsToPointCloud ( const rs2::points& points, Functor mapColorFunc )
  {
    typename pcl::PointCloud<PointT>::Ptr cloud ( new pcl::PointCloud<PointT> () );

    auto sp = points.get_profile ().as<rs2::video_stream_profile> ();
    cloud->width = sp.width ();
    cloud->height = sp.height ();
    cloud->is_dense = false;
    cloud->resize ( points.size () );

    const auto cloud_vertices_ptr = points.get_vertices ();
    const auto cloud_texture_ptr = points.get_texture_coordinates ();

#if OPENMP_LEGACY_CONST_DATA_SHARING_RULE
#pragma omp parallel for \
  default(none) \
  shared(cloud, mapColorFunc)
#else
#pragma omp parallel for \
  default(none) \
  shared(cloud, cloud_texture_ptr, cloud_vertices_ptr, mapColorFunc)
#endif
    for (std::size_t index = 0; index < cloud->size (); ++index)
    {
      const auto ptr = cloud_vertices_ptr + index;
      const auto uvptr = cloud_texture_ptr + index;
      auto& p = (*cloud)[index];

      p.x = ptr->x;
      p.y = ptr->y;
      p.z = ptr->z;

      mapColorFunc ( p, uvptr );
    }

    return cloud;
  }
`

**Comment by mvieth** [comment]
Seems like the problem is that the for-loop `index` is `std::size_t`. Changing it to `std::ptrdiff_t` should fix it (plus casting `static_cast<std::ptrdiff_t>(cloud->size())`). Unfortunately, Visual Studio does not accept unsigned variables here (I think the latest Visual Studio version does).
If you are interested, feel free to open a pull request to fix this on the PCL master branch.

**Comment by mynickmynick** [comment]
ok thanks for the opportunity

**Comment by mynickmynick** [comment]
yes that fixed it. i would like to check later or tomorrow with VS 2022 if it gives the same error or not (now I cannot)

**Comment by mynickmynick** [comment]
all comments are quite old except this one which I don't fully understand:
>It's been over a decade, and VS 2022's cl.exe still only supports OpenMP 2.0 via /openmp, unless one chooses /openmp:llvm, which [according to Microsoft](https://learn.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=msvc-170) is only supported for x64 targets and unsigned loop indices like in OpenMP 3.0. Kind of unfortunate... GCC/Clang is way ahead.

but it seems that openMP 3 is still not fully supported by MS VS

checking on MS i see
>Starting in Visual Studio 2019 version 16.9, you can use the experimental /openmp:llvm option instead of /openmp to target the LLVM OpenMP runtime. Support currently isn't available for production code, since the required libomp DLLs aren't redistributable. 

which I would not follow

 today i tried with MS VS 2022, Windows 10 with WITH_OPENMP=TRUE  and still the same error:
"......................\pcl\io\src\real_sense_2_grabber.cpp(302): error C3016: 'index': index variable in OpenMP 'for' statement must have signed integral type"

so shall I simply substitute
    for (std::size_t index = 0; index < cloud->size (); ++index)
with
    for (std::ptrdiff_t index = 0; index < static_cast<std::ptrdiff_t>(cloud->size()); ++index)

or do you prefer that I keep both with some sort of

`
#ifdef  WINDOWS 
    for (std::ptrdiff_t index = 0; index < static_cast<std::ptrdiff_t>(cloud->size()); ++index)
#else  
    for (std::size_t index = 0; index < cloud->size (); ++index)
#endif  
`

?

**Comment by mvieth** [comment]
No, just switching to ptrdiff_t is fine. It should be big enough, and I think we also use it in similar situations in other parts of PCL
